---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: install zabbix-agent
      apt:
        name: zabbix-agent
        state: latest

    - name: change server in conf
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server=127.0.0.1$'
        line: 'Server=192.168.122.243'

    - name: copy listenport-json.sh
      copy:
        src: files/zabbix/listenport-json.sh
        dest: /etc/zabbix
        mode: o=rx

    - name: create userparameter
      copy:
        dest: /etc/zabbix/zabbix_agentd.conf.d/up-listenport.conf
        content: 'UserParameter=listenport-json,/etc/zabbix/listenport-json.sh'

    - name: restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted
